"""init schema 17 tables

Revision ID: 8c7c0c95b0ce
Revises: 
Create Date: 2026-07-02 22:02:34.819532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7c0c95b0ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('base_unit', sa.String(length=20), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_items_normalized_name'), 'nutrition_items', ['normalized_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('social_provider', sa.String(length=20), nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_provider', 'social_id', name='uq_users_provider_social_id')
    )
    op.create_table('daily_nutrition_summaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meal_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'summary_date', name='uq_daily_summary_user_date')
    )
    op.create_table('eating_habits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('default_portion', sa.String(length=10), nullable=True),
    sa.Column('soup_preference', sa.String(length=10), nullable=True),
    sa.Column('sauce_preference', sa.String(length=10), nullable=True),
    sa.Column('leftover_frequency', sa.String(length=10), nullable=True),
    sa.Column('meal_goal', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('location_consents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('consent_status', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meal_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_images_user_id'), 'meal_images', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('lunch_time', sa.String(length=5), nullable=True),
    sa.Column('dinner_time', sa.String(length=5), nullable=True),
    sa.Column('weekly_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('push_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_push_tokens_user_device')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('terms_agreements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('terms_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_agreements_user_id'), 'terms_agreements', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('household_type', sa.String(length=20), nullable=True),
    sa.Column('goal_calories', sa.Integer(), nullable=False),
    sa.Column('goal_carbs', sa.Integer(), nullable=False),
    sa.Column('goal_protein', sa.Integer(), nullable=False),
    sa.Column('goal_fat', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_call_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('meal_image_id', sa.BigInteger(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meal_image_id'], ['meal_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_logs_user_id'), 'ai_call_logs', ['user_id'], unique=False)
    op.create_table('meal_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_image_id', sa.BigInteger(), nullable=True),
    sa.Column('meal_type', sa.String(length=10), nullable=False),
    sa.Column('eaten_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('total_calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meal_image_id'], ['meal_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_records_user_id'), 'meal_records', ['user_id'], unique=False)
    op.create_table('food_candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_image_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_call_log_id', sa.BigInteger(), nullable=True),
    sa.Column('nutrition_item_id', sa.BigInteger(), nullable=True),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('estimated_serving', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_call_log_id'], ['ai_call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_image_id'], ['meal_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrition_item_id'], ['nutrition_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_candidates_meal_image_id'), 'food_candidates', ['meal_image_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_record_id', sa.BigInteger(), nullable=False),
    sa.Column('nutrition_item_id', sa.BigInteger(), nullable=True),
    sa.Column('food_name', sa.String(length=100), nullable=False),
    sa.Column('serving_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calories', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meal_record_id'], ['meal_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nutrition_item_id'], ['nutrition_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_record_id'), 'meal_items', ['meal_record_id'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ai_call_log_id', sa.BigInteger(), nullable=True),
    sa.Column('meal_context', sa.JSON(), nullable=True),
    sa.Column('preferred_category', sa.String(length=30), nullable=True),
    sa.Column('recommendation_summary', sa.Text(), nullable=True),
    sa.Column('recommended_items', sa.JSON(), nullable=True),
    sa.Column('caution_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_call_log_id'], ['ai_call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_logs_user_id'), 'recommendation_logs', ['user_id'], unique=False)
    op.create_table('correction_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_record_id', sa.BigInteger(), nullable=False),
    sa.Column('meal_item_id', sa.BigInteger(), nullable=True),
    sa.Column('correction_type', sa.String(length=20), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meal_item_id'], ['meal_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_record_id'], ['meal_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_logs_meal_record_id'), 'correction_logs', ['meal_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_logs_meal_record_id'), table_name='correction_logs')
    op.drop_table('correction_logs')
    op.drop_index(op.f('ix_recommendation_logs_user_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_meal_items_meal_record_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_food_candidates_meal_image_id'), table_name='food_candidates')
    op.drop_table('food_candidates')
    op.drop_index(op.f('ix_meal_records_user_id'), table_name='meal_records')
    op.drop_table('meal_records')
    op.drop_index(op.f('ix_ai_call_logs_user_id'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_terms_agreements_user_id'), table_name='terms_agreements')
    op.drop_table('terms_agreements')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_meal_images_user_id'), table_name='meal_images')
    op.drop_table('meal_images')
    op.drop_table('location_consents')
    op.drop_table('eating_habits')
    op.drop_table('daily_nutrition_summaries')
    op.drop_table('users')
    op.drop_index(op.f('ix_nutrition_items_normalized_name'), table_name='nutrition_items')
    op.drop_table('nutrition_items')
    # ### end Alembic commands ###
